### ISSUE TITLE
Create Summary page for VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#943]
We will provide a mockup for this (assigning to curators first) - so please hold until wireframe is uploaded. Here are basic elements:

- possible grid display of criteria bar according to 1) met 2) not met and 3) not evaluated
- criteria definitions
- formula that gives you interpretation strength (e.g. PVS + 1S + 1M)

**Comment by selinad** [comment]
The wireframe for the VCI Summary page, modified based on our discussion, has been uploaded to Asana.  Matt and I have not had time to discuss the checkbox, but will do that and update the doc as necessary.  Please let us know if you have any questions.  @wrightmw if you have time for a quick review, please feel free to make any updates.

Thanks for everyone's help yesterday.
Selina

**Comment by jimmyzhen** [comment]
Hi @selinad,

Below is what I have so far for the summary page:
![image](https://cloud.githubusercontent.com/assets/6956310/18466879/6cd83612-7952-11e6-8f2e-ed80912ec389.png)

Need clarification for the following:
1. In the **Modified** column of the wireframe, what are those up/down arrows for and under what condition do we determine which one to use?
2. In the **Evaluation Status** column of the **"Met"** table, it looks like the intention is to concatenate the criteria code and modifier value for the display. However, we currently don't have any stored values for any criteria without the modifiers. In such cases, do we just simply parse the strength (e.g. strong, supporting) based on their classifications (e.g. benign-strong, benign-supporting)?

Thanks.

**Comment by selinad** [comment]
Wow @jimmyzhen - looking really sweet!  

Answers to questions:
* the arrow in modified is meant to symbolize how the curator modified the evaluation.  For instance, if it went from PM4 to PM4_Strong, it would go from a moderate to a strong classification, which would be one up arrow (increase in strength by one).  If is were a BP3 that goes to BP3_stand-alone, it would get an increase in strength by one as well.  Let me know if you need more clarification.  The idea is that if it went from moderate to supporting, it would get 1 down arrow.  If Strong to Supporting, 2 down arrows as it has to step down twice (Strong->Moderate->Supporting)
* I'm not quite sure what you mean by question 2 - let's talk.  If you mean if there was a BP4 without a modifier, then the strength would be P=supporting (but you might mean something else).

Comment:
Should we have a Modified column in bottom 2 tables with an N/A?  These may all go to 1 table at some point anyway....

Great work!

**Comment by jimmyzhen** [comment]
Hi @selinad,

Thank you for the clarifications!

Given your feedback, I've addressed the 2nd question of mine and the **Modified** column of the bottom 2 tables.
![image](https://cloud.githubusercontent.com/assets/6956310/18468750/2fd49dca-795a-11e6-8821-6759dd7b6ca5.png)

The implementation of the arrows might be tricky ;)

**Comment by selinad** [comment]
Looks great, @jimmyzhen !  I like having the Modified column on all three sections of the table.

Quick question - is it possible to remove the check from the red & green circles when criteria is not met or not evaluated?  The check implies "met."

If the arrows are tricky, can you think of some other way to show a change in strength?

Quick note: BA1 should have a stand-alone Evaluation status, not Strong:

BA1 = stand-alone
VS = very strong
S = strong
M = moderate
P = supporting

Lastly, I think the mockup had B/P with the B in green and the P in red.....do you think that's overkill? (not sure if you tried it)

Exciting - thank you!

**Comment by jimmyzhen** [comment]
For the very top table, with the help from @kgliu0101 on the rules/guidelines, the implementation of the arrows finally got resolved!

![image](https://cloud.githubusercontent.com/assets/6956310/18493515/d0ec0ac0-79c5-11e6-87fd-049478867c0d.png)

I am having a bit of tough time on implementing the sorting by strength. Kang has generously volunteered to help looking into it. So I have pushed my branch to the repo so that he can see the attempts I have tried so far. Thank you, @kgliu0101!

I am now moving on to implementing the other elements beneath the tables.

**Comment by jimmyzhen** [comment]
Hi @selinad,

Regarding your recent comment above, I have addressed them (see screenshot below):
![image](https://cloud.githubusercontent.com/assets/6956310/18494133/3b20b7bc-79c9-11e6-8509-e03738f39ea5.png)

In regards to BA1 associating a stand-alone Evaluation status, it is likely due to the fact that I don't have the latest criteria JSON file.

**Comment by selinad** [comment]
@jimmyzhen and @kgliu0101 - super on the arrows! Perfect!  (btw a BP4_stand-alone would have one up arrow - I assume you were just demonstrating 2 for that one)

Re icons: @jimmyzhen those are great !!! thank you!  That will be a quick way for people to know the status when we go to one table.

Now that I see it I think the green B and red P are a bit overwhelming. I prefer the black text. We can go to a hover over at some point (e.g. green check = benign criterion met)

**Comment by jimmyzhen** [comment]
@selinad The 2 up arrows are the result of our calculation. If going from "supporting" to "stand-alone" should be just 1 up arrow, then @kgliu0101 and I will need to revisit our calculation.

**Comment by selinad** [comment]
Wait - my bad.  You are correct - it does go up 2.  So sorry @jimmyzhen and @kgliu0101

**Comment by jimmyzhen** [comment]
Hi @selinad,

Please review the summary page via the following instance:
https://943-jz-summary-page-ce4bcc4-jzhen.demo.clinicalgenome.org

During your testing, please keep in mind that the "Mark as Provisional Interpretation" checkbox functionality is not yet fully implemented because such field is yet to be created in the schema to store the value. When the PR https://github.com/ClinGen/clincoded/pull/998 is merged, I will then complete the implementation.

**Comment by selinad** [comment]
Wow @jimmyzhen !  Thanks for all the hard work. So cool to have this up to test. I see the criteria bar and progress bar are integrated into this instance as well - so cool.  So far, they are working great.

Unfortunately, I ran into a snafu - when I hit the "View Summary" button, it switched to the "Return to Interpretation" button but did not go to the Summary page.  I hit the button again and it seemed to switch back to the "View Summary" button (no change in page).  Here's a screenshot I hope will help:

<img width="1428" alt="screen shot 2016-09-14 at 10 28 39 pm" src="https://cloud.githubusercontent.com/assets/11320314/18539294/f4d8ccc4-7aca-11e6-92c7-2cf7a72e0459.png">

**Comment by jimmyzhen** [comment]
Hi @selinad,

Is it true that either "BP4" or "PP3" can be selected at any given time, but not both? See screenshot below for reference:
![image](https://cloud.githubusercontent.com/assets/6956310/18539525/d0ddac98-7acc-11e6-9052-04ffbdfb3fa1.png)

**Comment by selinad** [comment]
Hi @jimmyzhen - yes, that is correct...

**Comment by jimmyzhen** [comment]
Hi @selinad,

I've fixed the bug and spun up a new instance for your review:
https://943-jz-summary-page-0264d3c-jzhen.demo.clinicalgenome.org

My apologies for the inconvenience!

**Comment by selinad** [comment]
Hey @jimmyzhen - great, thank you!

Buttons are working now and I can get to Summary page. Here are a few things:
- the benign circles are showing up red (see first big image, below)
- the arrows for benign criteria should be green, but they are red
- there are only 3 "not evaluated" criteria showing (4 met + 1 not met should leave 23 not evaluated left...).  Question: should we have the stuff that is below the table be above it? (not sure if this is a time consuming request) - I think it might be better since the table will be vertically long
- when I return to interpretation, I get the "Start New Interpretation" button but seem to be in interpretation mode since evaluation there - should see the Add disease button? (see second image).  If I click on the interpretation button, it seems like it erases the previous interpretation?  _There is definitely some funny business around the buttons_.  It seems they change by tab as well - so Add disease will appear on a different tab instead of "Start New Interpretation"  - having trouble figuring out a consistent pattern.
- also referring to the second image below, the View Summary button looks funny (so does the Return to Interpretation) - seems to have a not flat appearance...
- when a new pathogenicity is saved (from pull-down), can it update the "Calculated Pathogenicity" shown?  Nothing changes on the page....
- looks like the description for changing pathogenicity is required - we should have star by it
- text of the description box - small change: "If you selected a pathogenicity different from the Calculated Pathogenicity, provide a reason for the change here."  

<img width="329" alt="screen shot 2016-09-15 at 12 49 22 am" src="https://cloud.githubusercontent.com/assets/11320314/18542183/4ac22910-7ade-11e6-817f-28ce61899f0b.png">


<img width="753" alt="screen shot 2016-09-15 at 12 37 19 am" src="https://cloud.githubusercontent.com/assets/11320314/18541903/d91132f8-7adc-11e6-947d-1714a10cf1ea.png">

2nd image:
<img width="1180" alt="screen shot 2016-09-15 at 12 43 50 am" src="https://cloud.githubusercontent.com/assets/11320314/18542032/8aa33ebc-7add-11e6-84ea-a2df38e7fc2d.png">

**Comment by jimmyzhen** [comment]
Hi @selinad,

The circles and arrows for the benign criteria appear to be green as I just tested:
![image](https://cloud.githubusercontent.com/assets/6956310/18563435/73b55cd0-7b3c-11e6-8ed1-f7d2aaa30d8e.png)

Is it possible that you thought the P's should be benign?

Furthermore, in regards to the incorrect number of "not-evaluated" criteria, it looks like they would only be stored into the database if they are part of the criteria group being saved by the user.

**Comment by selinad** [comment]
oh, shoot!  Late night testing.  You are correct.  Sorry for the trouble.   I do think all the colors are a bit confusing, though, even at noon.  The green "PP" criteria are the problem.  We'll see what feedback we receive.

thx @jimmyzhen .

**Comment by selinad** [comment]
wrt to the Not yet evaluated criteria, thank you for the explanation.  That could definitely be misleading - is there a work-around that is not time-consuming?  If not, we may need to provide some sort of explanation....

**Comment by jimmyzhen** [comment]
@selinad In regards to your comment "when a new pathogenicity is saved (from pull-down), can it update the "Calculated Pathogenicity" shown? Nothing changes on the page....":

Is it really true that selecting a "Provisional Pathogenicity" value from the dropdown will alter the "Calculated Pathogenicity" value? Will it also affect the "Calculated Pathogenicity" value in the progress bar for that matter? (cc'ing @kgliu0101)

Can you also elaborate on the "looks like the description for changing pathogenicity is required - we should have star by it" comment?

**Comment by selinad** [comment]
Hi @jimmyzhen Sorry to be confusing - you are absolutely correct, it should not update the Calculated Pathogenicity.  Can it behave like the GDM?  It would be a "Provisional Interpretation" in addition to the Calculated Pathogenicity, so there would need to be a place to indicate that.

![screen shot 2016-09-15 at 5 38 02 pm](https://cloud.githubusercontent.com/assets/11320314/18571941/45f465d2-7b6b-11e6-927f-0452b7a91616.png)

I made the comment about the star as I thought that's what we do for required fields.  However, I don't see it above.  However, a save is not possible without a reason being entered.

For the Interpretation, the status would update (I think we decided that was OK) and have that value as well as the Calculated value - I'm pasting in below to show you what we do now for GDM.

![screen shot 2016-09-15 at 5 41 28 pm](https://cloud.githubusercontent.com/assets/11320314/18571976/ac453ad2-7b6b-11e6-81ce-e6bdfe87adae.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @kilodalton,

A big shoutout to @kgliu0101 who has helped me tremendously on getting the criteria sorted properly (by status and strength) on the summary page, even with the inclusion of those criteria that have not been saved into the evaluations object. Without his help, I wouldn't have been able to make summary page UIs to work the way we wanted.

Thank you, Kang!

**Comment by selinad** [comment]
Thank you both, @jimmyzhen and @kgliu0101, for all of your hard work  - great teamwork!  Looking forward to testing it out.

**Comment by jimmyzhen** [comment]
@selinad,

I am now in the process of spinning up a new instance for you to test. Will notify you when it is ready.

**Comment by jimmyzhen** [comment]
Hi @selinad,

You may review the updated summary page via the following instance:
https://943-jz-summary-page-640fdde-jzhen.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
Hi @selinad,

I've added the display of the modified pathogenicity and the provisional interpretation checkbox warning message to the summary page UI as discussed, along with some layout change of the form elements in the provisional section at the top of the summary page.

You may review the latest version of summary page via the following instance:
https://943-jz-summary-page-e745924-jzhen.demo.clinicalgenome.org

There is one minor bug that I have not been able to resolve at this time. The bug has to do with clicking on the "Return to interpretation" button, which shows the tab loaded initially with the page (e.g. the Basic Info tab normally) rather than the tab last viewed.

**Comment by selinad** [comment]
@jimmyzhen WOW!! Thank you for your dedication and working so hard on this!!  It's looking fantastic!  

The table looks super - I'll do some more evaluation permutations, but the sorting seems excellent (thank you to @kgliu0101 too!).  

- I notice that changing the pull-down value changes the field "Modified Pathogenicity" before a Save happens - could it do this after?  Especially because a description is required.
- When I click on "Mark as Provisional Interpretation" I think there is no feedback as to the fact something has changed. The status on the green bar will change once it is hooked up, so that will be good (is that this release?).  The only other thing that could help is to repeat the status right under "Modified Pathogenicity" so there would be a field "Status" right under that and it would say "In Progress" until the checkbox appears and then it would say "Provisional Interpretation" - not necessary this release unless a quick thing - if it is, I think it would be super helpful to the curator's experience and understanding of what is happening.
- Thank you for providing a note since I didn't get it to you yesterday - nicely done.  Only one small change : "...before it is marked" -> "...before it can be marked...."  Also, add another sentence after: "Please select "Return to Interpretation" to add a disease."
- I see why "Mark as Provisional Classification" is in bold, but I would prefer it be regular text
- the check box for the above is very hard to see for some reason, and I think even more so when not active - is there a quick way to make it more visible?
- is the "?" icon the same that will be used throughout the site for contextual help?  If so, my recommendation is it be blue.
- maybe a space between the Disease and the Marked for Provisional Classification....I think it will help distinguish between the report nature of the first section and the edit nature of the other.
- Can you describe which checks are in place right now wrt the likely path and path?  It seems like the checkbox is not active for that unless disease associated.  I know we can't do anything yet if they change pathogenicity, which is fine.  
- I need to mull on this, but I am thinking the "Mark as Provisional Interpretation should maybe go under the place where one can modify - it seems too disconnected to me at the moment.  I'll play around a bit more and weigh in again.  In a way this would be good so that the warning about adding disease appears in that same area....

Thanks again, @jimmyzhen for your super hard, superb work and to @kgliu0101 for his part in it as well!

**Comment by jimmyzhen** [comment]
Hi @selinad,

Here is the newest instance for you to review all the changes we discussed yesterday:
https://943-jz-summary-page-c744dcb-jzhen.demo.clinicalgenome.org/

**Comment by selinad** [comment]
Looking super, @jimmyzhen - as mentioned, I will do more thorough check shortly.

One quick thing:  I think I should be able to make this provisional (it's a likely benign), but it won't let me:

<img width="1161" alt="screen shot 2016-09-20 at 10 53 48 am" src="https://cloud.githubusercontent.com/assets/11320314/18682478/3d8d1f06-7f21-11e6-9b5a-efe56d22daa1.png">


<img width="1440" alt="screen shot 2016-09-20 at 10 59 34 am" src="https://cloud.githubusercontent.com/assets/11320314/18682505/5ce70b64-7f21-11e6-8ca3-4f78ab7b5665.png">

**Comment by jimmyzhen** [comment]
Hi @selinad,

I am also looking into this very issue as we speak.

**Comment by wrightmw** [comment]
@jimmyzhen Fantastic work. Looks great! I have a few comments:

- I agree with the point raised above by @selinad . Currently the text for the curator choosing a pathogenicity says 'Modify Pathogenicity (optional)', however it is not currently 'optional' because if the curators agrees with the 'Calculated Pathogenicity' and ticks the 'Mark as Provisional Interpretation (optional)' tickbox they are currently unable to 'Save' :
![screen shot 2016-09-20 at 1 01 28 pm](https://cloud.githubusercontent.com/assets/15131169/18687437/018caca6-7f35-11e6-9e6d-07a3275a869c.png)

- @selinad should the 'Calculated Pathogenicity' appear above the  'Modify Pathogenicity (optional)' pull-down so that it is clearer what they are modifying, and also clearer what they are marking as provisional (if they choose to do so)?

- If there are no criteria that have been evaluated as "not met" then the 'Criteria Evaluated as "Not Met"' table appears empty and the column headers are off kilter with the other tables. @selinad instead of an empty table should the headers be removed and we have a message, something along the lines of "No criteria were evaluated as "Not met""
![screen shot 2016-09-20 at 12 46 49 pm](https://cloud.githubusercontent.com/assets/15131169/18687721/476760c6-7f36-11e6-9327-b677c760d3eb.png)

**Comment by selinad** [comment]
Hi @wrightmw !  
- for now, I am ok with where Calculated Pathogenicity is, but if you feel strongly about it and it is quick for @jimmyzhen it's fine to add above
- I debated about the table thing, too - for now, I think it's nice to leave just so users know we track each of the 3 things.  I suppose if quick, we could add "None" as a row in an otherwise empty table....but I don't think necessary for this release.

**Comment by wrightmw** [comment]
@selinad re. 'Calculated Pathogenicity' ...I'm all for not making too many changes this close to a release... I'm happy to leave it as it is and then wait to hear the feedback from curators on how they'd prefer it to be displayed after the release

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Here is the latest instance to review:
https://943-jz-summary-page-52766b6-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment]
@jimmyzhen - thx!

Unfortunately, I am able to make a provisional interpretation on a 'Likely Patho..." when I haven't associated a disease:
<img width="1155" alt="screen shot 2016-09-20 at 10 55 18 pm" src="https://cloud.githubusercontent.com/assets/11320314/18699679/9b4d105e-7f87-11e6-8608-8f751fe1d509.png">

**Comment by jimmyzhen** [comment]
Hi @selinad,

Would you mind describing the steps you took to produce the bug? Thanks.

**Comment by selinad** [comment]
Hi @jimmyzhen. I started interpretation, evaluated several criteria to get calculated value of LP then went to summary and tried to make provisional interpretation.

**Comment by selinad** [comment]
@jimmyzhen - had we decided not to do checks at all this release?  You had had some in there, but maybe we took them out since we couldn't include them for the modification part....if so, apologies, and I will resume testing.

**Comment by jimmyzhen** [comment]
Hi @selinad,

We talked about putting checks in for this release. I had checks already implemented prior to our discussion, and the checks were thought to be working given the calculated pathogenicity and absence of associated disease. So we talked about adding the modified pathogenicity checks as well.

In any case, I have done a bit more work in the implementation, and it seems to work as expected:
![image](https://cloud.githubusercontent.com/assets/6956310/18716922/4cd67edc-7fd3-11e6-80c2-be7526e59405.png)

You may review it via the following new instance:
https://943-jz-summary-page-e19cee0-jzhen.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
And if you change the modified pathogenicity to "Likely Benign" or "Benign", the checkbox will be enabled:
![image](https://cloud.githubusercontent.com/assets/6956310/18717158/ef053874-7fd3-11e6-9fc6-123514c4557c.png)

**Comment by selinad** [comment]
Great - thanks @jimmyzhen - yes, now I remember the outcome of the conversation.

It performs correctly now - requires a disease if pathogenic - super!

Heading in and will test more - here's what I've done so far:
- evaluated to get calculated patho of "Pathogenic"
- tried to mark provisional - would not mark - perfect
- added diesase
- marked provisional - worked great 
- went to modify - selected VUS: update not allowed without reason - good!

If quick, a few things that would help ( at first I couldn't figure out why Update button wasn't available when I modified and hadn't entered reason :P):
- put "(optional" under "Modify Pathogenicity" and italicize without bold font: "_(optional)_"
- put "(_**required** for modified pathogenicity_)" under "Explain Reason(s) for change" - btw, I think "Reason(s)" should be in lower case

**Comment by selinad** [comment]
@wrightmw - one little thing:  If I have already saved a modification (so reason has been provided) and I go to modify it, a new reason not required....is this OK with you? (we don't have to address this issue, but something to think about)

**Comment by selinad** [comment]
One thing I can't check right now (we probably need to check when integrated with @mrmin123 's changes) - if I delete a disease from an interpretation and it is likely patho, what happens on Summary page?

**Comment by wrightmw** [comment]
@selinad I think that's fine for now. If they are modifying it to any other pathogenicity (different from the calculated pathogenicity) then they should really be required to add a new reason, but hopefully curators would want to do that anyway.

**Comment by jimmyzhen** [comment]
If a disease is no longer associated with the interpretation, the checkbox will be disabled if the calculated pathogenicity is "Likely Pathogenic", and the checkbox remains checked if it was previously marked as provisional.

**Comment by selinad** [comment]
wow - cool! thx @jimmyzhen - we can test that when merged....

**Comment by jimmyzhen** [comment]
Hi @selinad,

I've made the changes to the labels as you suggested:
![image](https://cloud.githubusercontent.com/assets/6956310/18723090/1c8e5dee-7fec-11e6-88b9-65254d7ffd1a.png)

**Comment by selinad** [comment]
Looks good @jimmyzhen - thx!  

The _(optional)_ is a bit low relative to the pull-down,  but we can deal with that next time.

thx! - S

**Comment by jimmyzhen** [comment]
I saw that as well so I've fixed it as we speak:
![image](https://cloud.githubusercontent.com/assets/6956310/18723712/9d3573c2-7fee-11e6-84d0-3e189c054477.png)

**Comment by selinad** [comment]
super! thx @jimmyzhen !

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton,

Would you think the following layout would make sense for curators?

![summary_provision_v1](https://cloud.githubusercontent.com/assets/6956310/18769767/e32f70ac-80e4-11e6-9a40-e6ab35ba20b7.png)

**Comment by wrightmw** [comment]
@jimmyzhen I much prefer this because it removes the unnecessary LHS white space

**Comment by selinad** [comment]
@jimmyzhen thx for thinking on this!

I do like it!  It seems like a reasonable workflow and I like how the left side is about the pathogenicity and the right is more about disease.

Let's do it! thx!

p.s. I especially like your reason for the change in pathogenicity ;-)

**Comment by jimmyzhen** [comment]
The new layout was actually a suggestion coming from @wrightmw! I simply just made it look prettier.

I have already merged @mrmin123's newest changes into my branch. So I will spin up a new instance for you all to review.

I don't think we need to wait for the new layout to let you to review the instance. I can just give you a screenshot when I updated the markup.

**Comment by selinad** [comment]
oops - I did not realize that. Brilliant, @wrightmw ! :)

Sounds good re instance - thx @jimmyzhen !

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The following new instance is ready for you to review the summary page along with Min's implementation of the Disease/MoI buttons:
https://943-jz-summary-page-2465ef0-jzhen.demo.clinicalgenome.org/

**Comment by jimmyzhen** [comment]
Also, I have updated the UI/form layout for the provision section as discussed previously. This change has **not** yet be committed to the latest instance provided above. But if you prefer to have it as well in the instance for testing, I can spin up another instance. Thanks.

![image](https://cloud.githubusercontent.com/assets/6956310/18802890/98f6c5d2-81a0-11e6-9aca-288d639534de.png)

**Comment by selinad** [comment]
@jimmyzhen - thx for this!  Looking great so far.

Still testing - quick thing.  Should a patho w/o a disease and no modified patho selected still have an operational save button?  

![screen shot 2016-09-23 at 4 06 47 pm](https://cloud.githubusercontent.com/assets/11320314/18803746/d71ddfa6-81a7-11e6-989d-fe3bfa916ffd.png)

**Comment by selinad** [comment]
So, I think what I did was test that I could not do patho and it changed to not allowing me to update (good), but then when I chose Likely benign, it wouldn't let me update...

![screen shot 2016-09-23 at 4 12 13 pm](https://cloud.githubusercontent.com/assets/11320314/18803809/8bd98ada-81a8-11e6-9489-757dafdcd98d.png)

**Comment by selinad** [comment]
Is it my imagination or is this button a different color? :-)
![screen shot 2016-09-23 at 4 16 40 pm](https://cloud.githubusercontent.com/assets/11320314/18803870/35295188-81a9-11e6-9654-e65edbff1da0.png)

**Comment by selinad** [comment]
@jimmyzhen now I have changed it to Likely pathogenic with a disease and the Update button doesn't work - there's something funny about the logic....I've been playing the role of an indecisive curator...

![screen shot 2016-09-23 at 4 20 51 pm](https://cloud.githubusercontent.com/assets/11320314/18803945/df3cb7fa-81a9-11e6-96e9-69ba7acec818.png)

**Comment by selinad** [comment]
Would it be trivial to link to the HPO term here: 
Autosomal dominant inheritance with maternal imprinting (HP:0012275) - also, I wouldn't mind the moi in _italics_ ;-)
![screen shot 2016-09-23 at 4 24 15 pm](https://cloud.githubusercontent.com/assets/11320314/18803984/37b9244a-81aa-11e6-802c-7e2c20d993f1.png)

**Comment by selinad** [comment]
For some reason, the moi button doesn't have an edit icon here even tho there is an moi associated with record already...

![screen shot 2016-09-23 at 4 25 55 pm](https://cloud.githubusercontent.com/assets/11320314/18804019/8468acac-81aa-11e6-848b-07be5b62c2cd.png)

**Comment by selinad** [comment]
@mrmin123 the bug with the edit button on moi happens when I hit hit "Return to Interpretation" from the Summary - it is edit when I go to Summary, and + when I return to the interpretation - did not notice that before....

**Comment by mrmin123** [comment]
@selinad Might be a new/uncaught issue introduced by the View Summary functionality (the Summary didn't exist when you were testing the MOI stuff before). @jimmyzhen do you have a handle on this or should I also take a look? I think you said you modified `actions.js` on your branch further...

**Comment by selinad** [comment]
@jimmyzhen - could you please change the title from "Evaluations Summary View" to  "Evaluation Summary" or "Interpretation Summary" ( @wrightmw feel free to vote) - I think we don't need the word "View" in there...sorry, I realized that's been bugging me! ;-)

**Comment by jimmyzhen** [comment]
@mrmin123 @selinad 

Let me investigate MoI button issue and see what the deal is. Will let you know whether this is something I can address.

**Comment by jimmyzhen** [comment]
Hi @selinad,

> Should a patho w/o a disease and no modified patho selected still have an operational save button?

Should the "Save" button be non-functional in this use case? Should it be just simply non-functional if the checkbox is disabled?

**Comment by jimmyzhen** [comment]
> So, I think what I did was test that I could not do patho and it changed to not allowing me to update (good), but then when I chose Likely benign, it wouldn't let me update...

Choosing a modified pathogenicity requires providing a reason in the textarea below. Otherwise, the "Save" or "Update" button will be disabled.

**Comment by jimmyzhen** [comment]
> Is it my imagination or is this button a different color?

It is the browser's default highlight color for buttons when it is selected. That color goes away when you deselect it by clicking on elsewhere on the page.

**Comment by selinad** [comment]
@jimmyzhen 

- if there is no disease and the Calculated patho is LP or P, the Mark as provisional is inactive.  One could hit the Save w/o modifying, but it would be pointless.  However, one could change to VUS, for instance, and then they could save and mark as provisional.  The question is whether the Save is active when there are no changes made, even tho changes can be made...maybe it's ok - what do we do in other places?  For instance, in GDM, if open Individual, is Save automatically active even if no values input?
- re: "Choosing a modified pathogenicity requires providing a reason in the textarea below. Otherwise, the "Save" or "Update" button will be disabled."  Good point - we need to make clearer for noobs like me.  Could a text string near Save/Update button appear once modification made - like "Supply reason for modification"?  Or is that logic too complicated this release?  
- re button: I wasn't selecting it - it's just how it was on the page....unless I am misunderstanding...

thx @jimmyzhen !

**Comment by jimmyzhen** [comment]
Hi @selinad, @mrmin123,

> For some reason, the moi button doesn't have an edit icon here even tho there is an moi associated with record already...

I have identified the bug and addressed it.

The summary page title has also been renamed to "Evaluation Summary".

**Comment by mrmin123** [comment]
@jimmyzhen awesome, thanks for the update!

**Comment by jimmyzhen** [comment]
Hi @selinad,

> Would it be trivial to link to the HPO term here: Autosomal dominant inheritance with maternal imprinting (HP:0012275)

Would you mind letting me know where the link should be going to?

**Comment by jimmyzhen** [comment]
> if there is no disease and the Calculated patho is LP or P, the Mark as provisional is inactive.  One could hit the Save w/o modifying, but it would be pointless.  However, one could change to VUS, for instance, and then they could save and mark as provisional.  The question is whether the Save is active when there are no changes made, even tho changes can be made...maybe it's ok - what do we do in other places?  For instance, in GDM, if open Individual, is Save automatically active even if no values input?

In GDM, the **Save** button is automatically active even when none of the input has any value initially. Upon clicking on the **Save** button, the form would alert the user about the required fields without any values.

In the case of the Summary page, since none of the input are required, we have no logic to stop the user(s) from submitting the form. If disabling the **Save** button makes more sense in this use case, I can certainly do so.

**Comment by selinad** [comment]
Hi @jimmyzhen - we link to HPO terms in the GDM.  Here is the site: http://compbio.charite.de/hpoweb/showterm?id=HP:0000118

Thanks re feedback on Save button - sounds like it's behavior is consistent with other places.  All good.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I've spun up a new instance for you to review the latest changes for the summary page:
https://943-jz-summary-page-8b2dc15-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen Thanks for this, it looks great. 
@selinad I one curator question, a minor thing:
- Do you think we should change the name of 'Evaluation Descriptions' in the Summary Table? As you scan across the table 'Criteria Descriptions' are descriptions of what the ACMG criteria codes mean, so it makes 'Evaluation Descriptions' seem like they may be descriptions of what the Evaluation Strengths mean (e.g. what does BS3_stand_alone mean)... should the header of this column be changed to something like 'Evaluation Explanation' so it makes it more obvious that it's the curator's explanation for choosing the Evaluation Strength and not a description of it? 'Explanation' is also the word used next to the text box where curators add this field.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

I am all for the **Evaluation Explanation** column header.

**Comment by selinad** [comment]
Hi @wrightmw good call! - we should be consistent with the text used for the evaluations box.

@jimmyzhen I'm testing - one quick thing - table columns don't line up between sections (where I thought they had previously?)

![screen shot 2016-09-27 at 9 36 45 am](https://cloud.githubusercontent.com/assets/11320314/18882963/39a31bc8-8496-11e6-8083-e4330b1123ad.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

I think the inconsistent column alignment is caused by the "Not-met" table that has no criteria in it. I will take a look and see if there is a quick fix.

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

See screenshot below for column header change and table column alignment fix:
![image](https://cloud.githubusercontent.com/assets/6956310/18884314/c0d75c80-849b-11e6-87e7-88fd9b19ce3a.png)

**Comment by selinad** [comment]
Nice!  Thanks, @jimmyzhen !

**Comment by jimmyzhen** [comment]
I am taking down the instance that I'd spun for this ticket since the instance for #1010 has already changes implemented for this ticket (e.g. https://1010-jz-disease-modal-2c85e97-jzhen.demo.clinicalgenome.org).

**Comment by selinad** [comment]
Hi @jimmyzhen - per our discussion - if I change the pull-down or the mark re provisional and leave the page w/o saving, when I return to the Summary, it shows the unsaved changes.  To be consistent with the evaluations and also since the last saved choices show (thus unsaved showing could be confusing), please change it so navigating off the Summary and back resets to last saved rather than unsaved....thx!

**Comment by selinad** [comment]
@jimmyzhen not a huge deal, but when it is LP (calculated) and I go to select modified value, the LP choice is still there - is there a quick way to make the calculated value not show?  If not, I can move to next release.  The calculated value would have to be removed from the pull-down 

![screen shot 2016-09-27 at 11 03 47 am](https://cloud.githubusercontent.com/assets/11320314/18885853/49cdf55c-84a2-11e6-88b7-3449080bcf82.png)

**Comment by selinad** [comment]
Hi @jimmyzhen per our most recent discussion - when a curator switches value to No Selection, please remove all text in the explain reason box and make it so it's not red.  Thank you!  I will move the pull-down comment above into R8.

thx!
Selina

**Comment by selinad** [comment]
@wrightmw what would you think of the "Mark as Provisional...." being changed to "Change status to "Provisional Interpretation"..."?  @jimmyzhen and I somewhat concerned people will think "mark" means they don't have to save....or, any other suggestions around this would be great if you agree it's a concern.  The other thought I had would be to move it below yellow note, closer to save button....

**Comment by selinad** [comment]
It's possible our use of italics has become a little out of sync for "In Progress" and "Provisional" - also mode of inheritance ...

In above image, "In progress" not in italics, but I think it will be in @kgliu0101 latest version - also, is the "P" supposed to be capitalized? (would be great to have a check that all this is consistent throughout site).

Mode of inheritance = "_None_" is in italics on the summary page and on the title, so should be OK, but also worth a check.

thx! -S

**Comment by wrightmw** [comment]
@selinad I like the idea of changing it from "Mark as Provisional..." to "Change status to "Provisional Interpretation"... I do think this is clearer

I'm not sure we need to move it adjacent to the Save button. To me it seems clear that the 'Save' button saves everything in that section

**Comment by jimmyzhen** [comment]
I have implemented the form value reset functionality:
1) reset textarea value if modified pathogenicity dropdown is changed to **No Selection**.
2) reset form values to last saved values if the user didn't save any changes and left the summary page.

I have also added the **Change status to "Provisional Interpretation"** label text change.

**Comment by selinad** [comment]
A thing of beauty - great job @jimmyzhen !

**Comment by wrightmw** [comment]
Looks and works fab!

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
